# application port
server:
  port: 7878
# eureka properties
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.104
  # producer application registry into eureka server
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:7777/eureka
# spring properties
spring:
  application:
    name: producer-A