server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.104
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:7777/eureka
spring:
  application:
    name: consumer-A