# application port
server:
  port: 8888
# eureka properties
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:7777/eureka
# spring properties
spring:
  application:
    name: consumer-A
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        consumerSink:
          destination: stream-demo
# feign enable hystrix
feign:
  hystrix:
    enabled: true
# add hyxtrix monitor
management:
  endpoints:
    web:
      exposure:
        include: ["hystrix.stream"]
  endpoint:
    hystrix:
      stream:
        enabled: true